name: Ski Locker Watcher
on:
  schedule:
    - cron: '0 10 * * *' # 10:00 AM UTC
  workflow_dispatch: # Allows you to press a button to test it

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_SECURE: ${{ secrets.SMTP_SECURE }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      ALERT_FROM_EMAIL: ${{ secrets.ALERT_FROM_EMAIL }}
      ALERT_TO_EMAIL: ${{ secrets.ALERT_TO_EMAIL }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Run Scraper
        run: |
          npm install
          node check_ski.js
      - name: Save Results
        run: |
          git config --global user.name "SkiBot"
          git config --global user.email "bot@github.com"
          git add public/logs.json
          git commit -m "Daily check update" || exit 0
          git push